#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 12 22:13:44 2019

@author: dell
"""


#import quandl
import numpy as np
#preprocessing-scaling
#cross-validation-splitting dada set into train and test
from sklearn import preprocessing,cross_validation  #split and scale
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.pyplot as plt 
import pandas as pd  
import seaborn as sns 
from sklearn.datasets import load_boston 
boston = load_boston() 

data = pd.DataFrame(boston.data) 
data.columns = boston.feature_names 
print(data.columns)


data['Price'] = boston.target 
data.head() 
x=boston.data
y=boston.target

#data.describe()
#data.info()

x_train,x_test,y_train,y_test=cross_validation.train_test_split(x,y,test_size=0.2)
regression_model=LinearRegression()
regression_model.fit(x_train,y_train)
confidence=regression_model.score(x_test,y_test)
print(confidence)
y_pred=regression_model.predict(x_test)